version: '3.7'
services:
  service-bus-events:
    build:
      context: .
      target: development
    ports:
      - "9229:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
